on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Test
        run: |
          cargo check
          cargo test --all
